const enum P1 {
  START_SIGNING = 0x01,
  ADD_TOKEN_IDS = 0x02,
  ADD_INPUT_BOX_FRAME = 0x03,
  ADD_INPUT_BOX_CONTEXT_EXTENSION_CHUNK = 0x04,
  ADD_DATA_INPUTS = 0x05,
  ADD_OUTPUT_BOX_START = 0x06,
  ADD_OUTPUT_BOX_ERGO_TREE_CHUNK = 0x07,
  ADD_OUTPUT_BOX_MINERS_FEE_TREE = 0x08,
  ADD_OUTPUT_BOX_CHANGE_TREE = 0x09,
  ADD_OUTPUT_BOX_TOKENS = 0x0a,
  ADD_OUTPUT_BOX_REGISTERS_CHUNK = 0x0b,
  CONFIRM = 0x0c,
  P2PK_SIGN = 0x0d,
}

const enum P2 {
  WITHOUT_TOKEN = 0x01,
  WITH_TOKEN = 0x02,
}
